DROP TABLE IF EXISTS stg_coins;
CREATE TABLE stg_coins (
    coin_id INTEGER NOT NULL,
    has_typological BOOLEAN NOT NULL,
    has_examples BOOLEAN NOT NULL,
    has_examples_pagination BOOLEAN NOT NULL,
    has_analysis BOOLEAN NOT NULL,
    coin_date_range VARCHAR NULL,
    denomination VARCHAR[] NULL,
    manufacture VARCHAR NULL,
    material VARCHAR[] NULL,
    object_type VARCHAR[] NULL,
    authority_name VARCHAR[] NULL,
    issuer_name VARCHAR[] NULL,
    stated_authority_name VARCHAR NULL,
    mint VARCHAR[] NULL,
    region VARCHAR[] NULL,
    obverse_controlmark VARCHAR NULL,
    obverse_deity VARCHAR[] NULL,
    obverse_legend TEXT NULL,
    obverse_portrait VARCHAR[] NULL,
    obverse_state VARCHAR[] NULL,
    obverse_type TEXT NULL,
    reverse_control_marks VARCHAR NULL,
    reverse_deity VARCHAR[] NULL,
    reverse_dynasty VARCHAR NULL,
    reverse_legend TEXT NULL,
    reverse_mintmark VARCHAR NULL,
    reverse_monogram VARCHAR NULL,
    reverse_officinamark VARCHAR[] NULL,
    reverse_portrait VARCHAR[] NULL,
    reverse_state VARCHAR[] NULL,
    reverse_symbol VARCHAR[] NULL,
    reverse_type TEXT NULL,
    average_axis NUMERIC NULL,
    average_diameter NUMERIC NULL,
    average_weight NUMERIC NULL,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (coin_id)
);
